// packages/core-vue3-vite/src/layout/Header.vue
<script lang="ts" setup>
import { RouterLink } from 'vue-router'
import { useGlobalModel } from "@/stores/useGlobalModel";

const { globalModel } = useGlobalModel();
</script>

<template>
  <header>
    <div class="wrapper">
      <nav>
        <RouterLink to="/">Home</RouterLink>
        |
        <RouterLink to="/about">About</RouterLink>
        |
        <RouterLink to="/profile">Profile</RouterLink>
        |
        <RouterLink to="/vue2">Vue2</RouterLink>
        |
        <RouterLink to="/vue3">Vue3</RouterLink>
        |
        <RouterLink to="/vue3-vite">Vue3-vite</RouterLink>
        |
        <RouterLink to="/react-umi">React-umi</RouterLink>
        Signed in as <strong>{{ globalModel.name }}</strong>
      </nav>
    </div>
  </header>
</template>

<style scoped>
header {
  line-height: 1.5;
}

nav {
  width: 100%;
  font-size: 12px;
  text-align: center;
  margin-top: 2rem;
}

nav a.router-link-exact-active {
  color: var(--color-text);
}

nav a.router-link-exact-active:hover {
  background-color: transparent;
}

nav a {
  display: inline-block;
  padding: 0 1rem;
  border-left: 1px solid var(--color-border);
}

nav a:first-of-type {
  border: 0;
}
</style>

// packages/core-react-umi/src/layout/Header.tsx
import React from 'react';
import { Link, useModel } from 'umi';

interface HeaderProps {
}

const Header: React.FC<HeaderProps> = () => {
  const { globalModel } = useModel('useGlobalModel');

  return (
    <div>
      <Link to="/">Home</Link> |
      <Link to="/about">About</Link> |
      <Link to="/profile">Profile</Link> |
      <Link to="/vue2">Vue2</Link> |
      <Link to="/vue3">Vue3</Link> |
      <Link to="/vue3-vite">Vue3-vite</Link> |
      <Link to="/react-umi">react-umi</Link>
      Signed in as <strong>{globalModel.name}</strong>
    </div>
  )
};
export default Header;
